language: python
python:
  - "3.9"
install:
  - pip install -r requirements.txt
jobs:
  include:
    - stage: lint
      script: pytest --flake8
    - stage: test
      script: python -m unittest discover test -v
